sudo: required
services: 
  - docker

before_install:
  - docker build -t arteaga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run arteaga/react-test npm test -- --coverage

after_success: 
  - docker build -t arteaga/multi-client ./client
  - docker build -t arteaga/multi-nginx ./nginx
  - docker build -t arteaga/multi-server ./server
  - docker build -t arteaga/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push arteaga/multi-client
  - docker push arteaga/multi-nginx
  - docker push arteaga/multi-server
  - docker push arteaga/multi-worker

deploy:
  provides: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-899145525820
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY