sudo: required
services: 
  - docker

before_install:
  - docker build -t arteaga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run arteaga/react-test npm test -- --coverage

after_success: 
  - docker build -t arteaga/multi-client ./client
  - docker build -t arteaga/multi-nginx ./nginx
  - docker build -t arteaga/multi-server ./server
  - docker build -t arteaga/multi-workers ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push tehm to docker hub
  - docker push arteaga/multi-client
  - docker push arteaga/multi-nginx
  - docker push arteaga/multi-server
  - docker push arteaga/multi-worker
  